PlayerData:
    Money:
        # Money balance player receives when they first join
        Balance: 1000
Command:
    Help:
        # Shows all aliases of the commands.
        Aliases:
            Enable: true
Island:
    World:
        Normal:
            Name: "island_normal_world"
        Nether:
            Name: "island_nether_world"
            Enable: true
    Member:
        # Max amount of players allowed to be in a team.
        Capacity: 12
    WorldBorder:
        # Generates a worldborder around Islands.
        # [!] WorldBorders will not show in Nether world due to centring bug
        #     with some Spigot builds.
        Enable: true
        # Prevent blocks being placed that would go outside of the Island border
        # Pistons | Dispensers | Liquid Flow
        Block: true
    Spawn:
        # Prevents blocks being placed inside the location where players spawn on
        # an Island. When setting the spawn points, this option when enabled will
        # require the player to position themselves at the centre of the block.
        # [!] Recommended to use especially to prevent players glitching in blocks
        #     and to prevent liquid flow at spawn point.
        Protection: true
    Block:
        Piston:
            # Prevent Piston blocks being retracted or extended when connected to a circuit
            # [!] Prevents Pistons extending out of Island border bug
            Connected:
                Retract: false
                Extent: false
    Invite:
        # Time until Island invite expires
        Time: 300
    Visitor:
        # When an Island is unloaded if enabled players won't be able to visit the Island
        # even if it's open.
        # [!] Enabling will prevent possible memory leak issues affecting performance.
        Unload: false
        # Upon Island creation is the Island open to visit?
        Open: false
        # Allow players to vote for Islands. This will filter Islands with more votes first
        # in the Visit Island menu.
        Vote: true
        Welcome:
            # When disabled Island owners or operators will not be able to set a Welcome Message
            # and visitors will not see the Welcome Message.
            Enable: true
            # Maximum lines allowed for Welcome Message
            Lines: 6
            # Length allowed for each line
            Length: 30
        Signature:
            # When disabled Island owners or operators will not be able to set a Signature and
            # a Signature will not be visible in the Island Visit menu.
            Enable: true
            # Maximum lines allowed for Signature
            Lines: 6
            # Length allowed for each line
            Length: 30
        # Max amount of players allowed at a Island. This also includes Island Members.
        # [!] Set to -1 for unlimited capacity.
        Capacity: 25
        # Allow Island Operators or Owners to ban players from their Island.
        Banning: true
    Biome:
        # Default Biome set when a player creates an Island
        # Biomes Available:
        # PLAINS | FOREST | SWAMPLAND | DESERT | COLD_BEACH
        # JUNGLE | ROOFED_JUNGLE
        Default:
            Type: Plains
        Cooldown: 900
    Weather:
        Default:
            # The weather and time will operate the same weather and time as the world.
            # If disabled, the weather and time will be fixed to the weather and time
            # options.
            Synchronised: true
            # Make sure the time is one of the choices below
            # 0 | 1000 | 6000 | 12000 | 13000 | 18000
            Time: 6000
            Weather: Clear
        # Prevents ice and snow layer blocks being set in snowy conditions.
        # [!] Recommended to keep this disabled to prevent confusion if island weather
        #     and time is not synchronised.
        IceAndSnow: false
    Levelling:
        # Island Level Points divided by value
        Division: 100
        # Time until Island level rescan expires
        Cooldown: 60
    Confirmation:
        # Time until confirmation expires for island ownership and island deletion
        # confirmations.
        Timeout: 10
    Ownership:
        Transfer:
            Role:
                # When Island ownership is transfer to a different player the previous
                # Island owner will become an operator.
                Operator: true
        Password:
            # When ownership has been assigned to a player the Island password will
            # be reset.
            Reset: true
    Void:
        Teleport:
            # Prevents players from being killed by the Void when at their Island.
            Enable: true
            # The Y position that the player is teleported when reached.
            Offset: 30
    Death:
        AutoRespawn: true
        Respawn:
            # When a Player respawns after dying at an Island decide where they respawn.
            # [!] If Enabled Players will respawn at the Island they died at. If Disabled
            #     Players will respawn at the Spawn location.
            Island: true
    Admin:
        Structure:
            # Item Material used to select positions for a structure.
            Selector: "DIAMOND_AXE"
    Scoreboard:
        Enable: true
# Stuff you shouldn't change
World:
  Normal:
    nextAvailableLocation:
      x: 0.0
      z: 0.0
  Nether:
    nextAvailableLocation:
      x: 0.0
      z: 0.0