name: SkyBlock
main: me.goodandevil.skyblock.SkyBlock
version: 60
api-version: 1.13
description: A unique SkyBlock plugin
author: GoodAndEvil
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault, Coins, LeaderHeads]
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Island command
        aliases: [is]